name: Learning-Expression
on: [push]
run-name: "expr action by ${{ github.actor }} event : ${{ github.event_name}}"
jobs:
    using-exp-and-context:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout-code
              uses: actions/checkout@v2
            - name: expressions
              id: expr
              run: |
                echo ${{ true && false || true }}
                echo ${{ 'This is a expression' }}
            - name: dump-context
              run: |
                echo "${{ toJson(github) }}"
                echo "${{ toJson(env) }}"