name: Second Workflow
on: [push, pull_request]

jobs:
    install-python-pip:
        runs-on: ubuntu-latest
        steps:
            - name: Install Python and pip
              run: |
                sudo apt-get update
                sudo apt-get install -y python3 python3-pip
            

    install-required-lib:
        runs-on: ubuntu-latest
        needs: install-python-pip
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Install requirement.txt
              run: pip3 install -r requirements.txt
