name: stale & PR
on: 
    schedule:
      - cron: '0 0 * * 0'  # Runs every Sunday at midnight
    pull_request:
    push:

jobs:
    stale-and-PR:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout-code
              uses: actions/checkout@v2

            - name: stale action
              uses: actions/stale@v6
              with:
                stale-issue-message: "This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Thank you for your contributions."
                days-before-stale: 2
                days-before-close: 7